language: python
branches:
    only:
        - master
        - develop
        
python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
script:
    - py.test --cov=pyswagger --cov-config=.coveragerc pyswagger/tests
after_success:
    - coveralls

